2020-10-26 12:02:22.595 - [Info] MITM Version: 1.26
2020-10-26 12:02:22.606 - [Info] Auto Access Enabled: true
2020-10-26 12:02:22.607 - [Debug] [Init] Auto Access Barrier: true
2020-10-26 12:02:22.652 - [Info] SSH man-in-the-middle server for 172.20.0.201 listening on 0.0.0.0:10000
2020-10-26 12:15:43.243 - [Debug] [Connection] Attacker connected: 190.2.137.62 | Client Identification: SSH-2.0-sshlib-0.1
2020-10-26 12:15:44.380 - [Debug] [Auth] Attacker 190.2.137.62 trying to authenticate with "password"
2020-10-26 12:15:44.381 - [Debug] [Auto Access] Attacker: 190.2.137.62, Threshold: 1, Attempts: 1
2020-10-26 12:15:44.381 - [Debug] [Auto Access] Compromising the honeypot
2020-10-26 12:15:44.381 - [Debug] [Auto Access] Adding the following credentials: "root:root"
2020-10-26 12:15:44.564 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-26 12:15:44.564 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.201
2020-10-26 12:15:59.888 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-26 12:16:17.100 - [Debug] [Connection] Attacker closed connection
2020-10-26 12:16:17.116 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-26 12:16:17.117 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-26 12:20:56.367 - [Debug] [Connection] Attacker connected: 141.98.9.32 | Client Identification: SSH-2.0-OpenSSH_7.3
2020-10-26 12:20:57.807 - [Debug] [Auth] Attacker 141.98.9.32 trying to authenticate with "password"
2020-10-26 12:20:57.808 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2020-10-26 12:20:57.809 - [Debug] [Auth] Attacker: 141.98.9.32 has so far made 1 attempts. Remaining: 5 attempts
2020-10-26 12:20:58.350 - [Debug] [Connection] Attacker closed the connection
2020-10-26 12:20:59.496 - [Debug] [Connection] Attacker connected: 141.98.9.33 | Client Identification: SSH-2.0-OpenSSH_7.3
2020-10-26 12:21:00.995 - [Debug] [Auth] Attacker 141.98.9.33 trying to authenticate with "password"
2020-10-26 12:21:00.996 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-26 12:21:00.997 - [Debug] [Auth] Attacker: 141.98.9.33 has so far made 1 attempts. Remaining: 5 attempts
2020-10-26 12:21:01.267 - [Debug] [Connection] Attacker closed the connection
