2020-11-13 08:44:37.278 - [Info] MITM Version: 1.26
2020-11-13 08:44:37.281 - [Info] Auto Access Enabled: true
2020-11-13 08:44:37.281 - [Debug] [Init] Auto Access Barrier: true
2020-11-13 08:44:37.296 - [Info] SSH man-in-the-middle server for 172.20.0.202 listening on 0.0.0.0:10001
2020-11-13 08:45:11.035 - [Debug] [Connection] Attacker connected: 81.70.43.103 | Client Identification: SSH-2.0-libssh-0.6.3
2020-11-13 08:45:16.676 - [Debug] [Auth] Attacker 81.70.43.103 trying to authenticate with "password"
2020-11-13 08:45:16.676 - [Debug] [Auto Access] Attacker: 81.70.43.103, Threshold: 1, Attempts: 1
2020-11-13 08:45:16.677 - [Debug] [Auto Access] Compromising the honeypot
2020-11-13 08:45:16.677 - [Debug] [Auto Access] Adding the following credentials: "root:roottoor"
2020-11-13 08:45:16.789 - [Debug] [Auth] Valid credentials - Password Authentication
2020-11-13 08:45:16.790 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.202
2020-11-13 08:45:26.696 - [Debug] [Connection] Attacker closed the connection
2020-11-13 08:45:28.125 - [Debug] [Connection] Attacker connected: 106.53.26.197 | Client Identification: SSH-2.0-libssh-0.6.3
2020-11-13 08:45:31.724 - [Debug] [Auth] Attacker 106.53.26.197 trying to authenticate with "password"
2020-11-13 08:45:31.725 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-11-13 08:45:31.725 - [Debug] [Auth] Attacker: 106.53.26.197 has so far made 1 attempts. Remaining: 5 attempts
2020-11-13 08:45:33.099 - [Debug] [Connection] Attacker closed the connection
2020-11-13 08:45:34.504 - [Info] Exiting...
2020-11-13 08:45:34.504 - [Debug] Cleaning up...
No auth in progress
Attacker IP: 188.226.192.115
