2020-10-27 22:52:33.198 - [Info] MITM Version: 1.26
2020-10-27 22:52:33.204 - [Info] Auto Access Enabled: true
2020-10-27 22:52:33.205 - [Debug] [Init] Auto Access Barrier: true
2020-10-27 22:52:33.233 - [Info] SSH man-in-the-middle server for 172.20.0.202 listening on 0.0.0.0:10001
2020-10-27 22:54:48.734 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-libssh_0.4.8
2020-10-27 22:54:49.984 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-27 22:54:49.985 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-27 22:54:50.274 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-27 22:54:50.275 - [Debug] [Auto Access] Attacker: 193.105.134.45, Threshold: 1, Attempts: 1
2020-10-27 22:54:50.275 - [Debug] [Auto Access] Compromising the honeypot
2020-10-27 22:54:50.275 - [Debug] [Auto Access] Adding the following credentials: "admin:letmein"
2020-10-27 22:54:50.715 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-27 22:54:50.716 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.202
2020-10-27 22:54:50.817 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-27 22:54:51.976 - [Debug] [Connection] Attacker closed connection
2020-10-27 22:54:52.534 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-27 22:54:52.535 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-27 22:57:01.136 - [Debug] [Connection] Attacker connected: 195.3.147.47 | Client Identification: SSH-2.0-PuTTY_Release_0.63
2020-10-27 22:57:02.276 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "none"
2020-10-27 22:57:02.277 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-27 22:57:02.536 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "password"
2020-10-27 22:57:02.537 - [Debug] [Auth] Attacker authentication error: Invalid credentials - Password Authentication Failure
2020-10-27 22:57:02.538 - [Debug] [Auth] Attacker: 195.3.147.47 has so far made 1 attempts. Remaining: 5 attempts
2020-10-27 22:57:02.797 - [Debug] [Connection] Attacker closed the connection
2020-10-27 22:59:04.118 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-OpenSSH_6.2
2020-10-27 22:59:05.738 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-27 22:59:05.738 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-27 22:59:06.019 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-27 22:59:06.020 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-27 22:59:06.021 - [Debug] [Auth] Attacker: 193.105.134.45 has so far made 1 attempts. Remaining: 5 attempts
2020-10-27 22:59:06.298 - [Debug] [Connection] Attacker closed the connection
