2020-10-28 12:57:44.426 - [Info] MITM Version: 1.26
2020-10-28 12:57:44.433 - [Info] Auto Access Enabled: true
2020-10-28 12:57:44.433 - [Debug] [Init] Auto Access Barrier: true
2020-10-28 12:57:44.455 - [Info] SSH man-in-the-middle server for 172.20.0.202 listening on 0.0.0.0:10001
2020-10-28 12:58:40.627 - [Debug] [Connection] Attacker connected: 109.236.91.85 | Client Identification: SSH-2.0-Nmap_SSH2_Hostkey  
2020-10-28 12:58:41.772 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "none"
2020-10-28 12:58:41.773 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 12:58:41.997 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "password"
2020-10-28 12:58:41.999 - [Debug] [Auto Access] Attacker: 109.236.91.85, Threshold: 1, Attempts: 1
2020-10-28 12:58:41.999 - [Debug] [Auto Access] Compromising the honeypot
2020-10-28 12:58:42.000 - [Debug] [Auto Access] Adding the following credentials: "sshd:service"
2020-10-28 12:58:42.337 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-28 12:58:42.337 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.202
2020-10-28 12:58:42.436 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-28 12:58:43.987 - [Debug] [Connection] Attacker closed connection
2020-10-28 12:58:44.015 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-28 12:58:44.017 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-28 13:01:37.853 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-OpenSSH_6.0
2020-10-28 13:01:39.288 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-28 13:01:39.289 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 13:01:39.558 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-28 13:01:39.558 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-28 13:01:39.559 - [Debug] [Auth] Attacker: 193.105.134.45 has so far made 1 attempts. Remaining: 5 attempts
2020-10-28 13:01:39.828 - [Debug] [Connection] Attacker closed the connection
2020-10-28 13:01:59.742 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-PuTTY_Release_0.64
2020-10-28 13:02:00.923 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-28 13:02:00.923 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 13:02:01.203 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-28 13:02:01.203 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-28 13:02:01.204 - [Debug] [Auth] Attacker: 193.105.134.45 has so far made 1 attempts. Remaining: 5 attempts
2020-10-28 13:02:01.483 - [Debug] [Connection] Attacker closed the connection
