2020-11-20 19:02:52.355 - [Info] MITM Version: 1.26
2020-11-20 19:02:52.359 - [Info] Auto Access Enabled: true
2020-11-20 19:02:52.360 - [Debug] [Init] Auto Access Barrier: true
2020-11-20 19:02:52.372 - [Info] SSH man-in-the-middle server for 172.20.0.201 listening on 0.0.0.0:10000
2020-11-20 19:02:57.821 - [Debug] [Connection] Attacker connected: 85.202.161.110 | Client Identification: SSH-2.0-libssh-0.6.3
2020-11-20 19:02:58.874 - [Debug] [Auth] Attacker 85.202.161.110 trying to authenticate with "password"
2020-11-20 19:02:58.875 - [Debug] [Auto Access] Attacker: 85.202.161.110, Threshold: 1, Attempts: 1
2020-11-20 19:02:58.875 - [Debug] [Auto Access] Compromising the honeypot
2020-11-20 19:02:58.875 - [Debug] [Auto Access] Adding the following credentials: "ts3:12345"
2020-11-20 19:02:59.097 - [Debug] [Auth] Valid credentials - Password Authentication
2020-11-20 19:02:59.097 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.201
2020-11-20 19:03:06.935 - [Debug] [Connection] Attacker connected: 181.48.28.13 | Client Identification: SSH-2.0-libssh-0.6.3
2020-11-20 19:03:07.490 - [Debug] [Auth] Attacker 181.48.28.13 trying to authenticate with "password"
2020-11-20 19:03:07.491 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-11-20 19:03:07.492 - [Debug] [Auth] Attacker: 181.48.28.13 has so far made 1 attempts. Remaining: 5 attempts
2020-11-20 19:03:07.686 - [Debug] [Connection] Attacker closed the connection
2020-11-20 19:03:08.883 - [Debug] [Connection] Attacker closed the connection
2020-11-20 19:03:17.042 - [Info] Exiting...
2020-11-20 19:03:17.042 - [Debug] Cleaning up...
No auth in progress
Attacker IP: 106.52.152.16
