2020-11-18 10:36:07.890 - [Info] MITM Version: 1.26
2020-11-18 10:36:07.894 - [Info] Auto Access Enabled: true
2020-11-18 10:36:07.894 - [Debug] [Init] Auto Access Barrier: true
2020-11-18 10:36:07.906 - [Info] SSH man-in-the-middle server for 172.20.0.203 listening on 0.0.0.0:10002
2020-11-18 10:42:14.339 - [Debug] [Connection] Attacker connected: 171.239.255.165 | Client Identification: SSH-2.0-AsyncSSH_2.1.0
2020-11-18 10:42:16.150 - [Debug] [Auth] Attacker 171.239.255.165 trying to authenticate with "none"
2020-11-18 10:42:16.150 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-11-18 10:42:16.670 - [Debug] [Auth] Attacker 171.239.255.165 trying to authenticate with "password"
2020-11-18 10:42:16.670 - [Debug] [Auto Access] Attacker: 171.239.255.165, Threshold: 1, Attempts: 1
2020-11-18 10:42:16.671 - [Debug] [Auto Access] Compromising the honeypot
2020-11-18 10:42:16.671 - [Debug] [Auto Access] Adding the following credentials: "root:@"
2020-11-18 10:42:16.796 - [Debug] [Auth] Valid credentials - Password Authentication
2020-11-18 10:42:16.796 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.203
2020-11-18 10:42:19.173 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-11-18 10:42:52.888 - [Debug] [Connection] Attacker connected: 116.110.72.96 | Client Identification: SSH-2.0-AsyncSSH_2.1.0
2020-11-18 10:42:56.198 - [Debug] [Auth] Attacker 116.110.72.96 trying to authenticate with "none"
2020-11-18 10:42:56.199 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-11-18 10:42:56.653 - [Debug] [Auth] Attacker 116.110.72.96 trying to authenticate with "password"
2020-11-18 10:42:56.653 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-11-18 10:42:56.654 - [Debug] [Auth] Attacker: 116.110.72.96 has so far made 1 attempts. Remaining: 5 attempts
2020-11-18 10:42:57.110 - [Debug] [Connection] Attacker closed the connection
2020-11-18 10:43:20.231 - [Debug] [Connection] Client error on ssh server
2020-11-18 10:43:20.232 - [Debug] [Connection] Attacker closed connection
2020-11-18 10:43:20.237 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-11-18 10:43:20.238 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-11-18 10:44:59.025 - [Debug] [Connection] Attacker connected: 116.110.72.96 | Client Identification: SSH-2.0-AsyncSSH_2.1.0
2020-11-18 10:45:00.339 - [Debug] [Auth] Attacker 116.110.72.96 trying to authenticate with "none"
2020-11-18 10:45:00.339 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-11-18 10:45:01.024 - [Debug] [Auth] Attacker 116.110.72.96 trying to authenticate with "password"
2020-11-18 10:45:01.024 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-11-18 10:45:01.025 - [Debug] [Auth] Attacker: 116.110.72.96 has so far made 1 attempts. Remaining: 5 attempts
2020-11-18 10:45:01.484 - [Debug] [Connection] Attacker closed the connection
2020-11-18 10:47:20.482 - [Info] Exiting...
2020-11-18 10:47:20.483 - [Debug] Cleaning up...
