2020-10-25 15:44:30.646 - [Info] MITM Version: 1.26
2020-10-25 15:44:30.654 - [Info] Auto Access Enabled: true
2020-10-25 15:44:30.654 - [Debug] [Init] Auto Access Barrier: true
2020-10-25 15:44:30.677 - [Info] SSH man-in-the-middle server for 172.20.0.202 listening on 0.0.0.0:10001
2020-10-25 15:47:09.241 - [Debug] [Connection] Attacker connected: 109.236.91.85 | Client Identification: SSH-2.0-PuTTY_Release_0.62
2020-10-25 15:47:10.805 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "none"
2020-10-25 15:47:10.806 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-25 15:47:11.026 - [Debug] [Auth] Attacker 109.236.91.85 trying to authenticate with "password"
2020-10-25 15:47:11.029 - [Debug] [Auto Access] Attacker: 109.236.91.85, Threshold: 1, Attempts: 1
2020-10-25 15:47:11.029 - [Debug] [Auto Access] Compromising the honeypot
2020-10-25 15:47:11.029 - [Debug] [Auto Access] Adding the following credentials: "123:123"
2020-10-25 15:47:11.662 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-25 15:47:11.663 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.202
2020-10-25 15:47:27.010 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-25 15:47:28.534 - [Debug] [Connection] Attacker closed connection
2020-10-25 15:47:28.539 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-25 15:47:28.539 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-25 15:48:48.388 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-PuTTY_Release_0.61
2020-10-25 15:48:49.586 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-25 15:48:49.586 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-25 15:48:49.866 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-25 15:48:49.867 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-25 15:48:49.868 - [Debug] [Auth] Attacker: 193.105.134.45 has so far made 1 attempts. Remaining: 5 attempts
2020-10-25 15:48:50.156 - [Debug] [Connection] Attacker closed the connection
2020-10-25 15:49:30.458 - [Debug] [Connection] Attacker connected: 193.105.134.45 | Client Identification: SSH-2.0-PuTTY_Release_0.62.1
2020-10-25 15:49:32.022 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "none"
2020-10-25 15:49:32.022 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-25 15:49:32.292 - [Debug] [Auth] Attacker 193.105.134.45 trying to authenticate with "password"
2020-10-25 15:49:32.293 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-25 15:49:32.295 - [Debug] [Auth] Attacker: 193.105.134.45 has so far made 1 attempts. Remaining: 5 attempts
2020-10-25 15:49:32.562 - [Debug] [Connection] Attacker closed the connection
2020-10-25 15:50:39.323 - [Debug] [Connection] Attacker connected: 62.98.82.208 | Client Identification: SSH-2.0-OpenSSH_7.9p1 Raspbian-10+deb10u2
2020-10-25 15:50:39.428 - [Debug] [Connection] Attacker connected: 62.98.82.208 | Client Identification: SSH-2.0-OpenSSH_7.9p1 Raspbian-10+deb10u2
2020-10-25 15:50:40.151 - [Debug] [Auth] Attacker 62.98.82.208 trying to authenticate with "none"
2020-10-25 15:50:40.151 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-25 15:50:40.224 - [Debug] [Auth] Attacker 62.98.82.208 trying to authenticate with "none"
2020-10-25 15:50:40.225 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-25 15:50:40.445 - [Debug] [Auth] Attacker 62.98.82.208 trying to authenticate with "password"
2020-10-25 15:50:40.446 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-25 15:50:40.447 - [Debug] [Auth] Attacker: 62.98.82.208 has so far made 1 attempts. Remaining: 5 attempts
2020-10-25 15:50:40.520 - [Debug] [Auth] Attacker 62.98.82.208 trying to authenticate with "password"
2020-10-25 15:50:40.520 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-25 15:50:40.521 - [Debug] [Auth] Attacker: 62.98.82.208 has so far made 1 attempts. Remaining: 5 attempts
2020-10-25 15:50:40.725 - [Debug] [Connection] Attacker closed the connection
2020-10-25 15:50:40.803 - [Debug] [Connection] Attacker closed the connection
2020-10-25 15:50:44.816 - [Debug] [Connection] Attacker connected: 195.3.147.47 | Client Identification: SSH-2.0-PuTTY_Release_0.63
2020-10-25 15:50:45.988 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "none"
2020-10-25 15:50:45.988 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-25 15:50:46.257 - [Debug] [Auth] Attacker 195.3.147.47 trying to authenticate with "password"
2020-10-25 15:50:46.258 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-25 15:50:46.260 - [Debug] [Auth] Attacker: 195.3.147.47 has so far made 1 attempts. Remaining: 5 attempts
2020-10-25 15:50:46.527 - [Debug] [Connection] Attacker closed the connection
